project:
  type: website
  output-dir: docs
  resources: data

website:
  title: "Julius Welzel"
  image: images/eeg.jpg
  # cookie-consent: true
  search: 
    location: navbar
    type: textbox
  navbar:
    background: primary
    pinned: true
    left:
      # - text: About
      #   href: index.qmd
      - text: Research 
        href: research/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Software
        href: software/index.qmd
      - text: Positions
        href: positions/index.qmd
      - text: CV
        href: cv/index.qmd
    right:
    - icon: envelope
      aria-label: email
      href: "mailto:julius.welzel@gmail.com"
    - icon: github
      href: https://github.com/JuliusWelze
    - icon: google
      href: https://scholar.google.com/citations?user=CWxKXBcAAAAJ&hl
    - icon: mastodon
      href: https://fosstodon.org/@JuliusWelzel
  page-footer: 
    left: "Copyright 2023, Julius Welzel" 
    right: 
      - text: Impressum
        href: impressum/index.qmd

format:
  html:
    fontsize: 1.1em
    theme:
      light: flatly
      dark: darkly
    css: styles.css