---
title: Scientific Publications
excerpt: "A list of my scientific publications"
toc-location: right
---

## 2024

- Lang, C., van Dieen, J. H., Brodie, M. A., **Welzel, J.**, Maetzler, W., Singh, N. B., & Ravi, D. K. (2024). [Complexities and challenges of translating intervention success to real-world gait in people with Parkinson’s disease. *Frontiers in Neurology, 15.*](https://www.frontiersin.org/journals/neurology/articles/10.3389/fneur.2024.1455692/full)

- Abedinifar, M., **Welzel, J.**, Hansen, C., Maetzler, W., & Romijnders, R. (2024). [KielMAT: Kiel Motion Analysis Toolbox – An open-source Python toolbox for analyzing neurological motion data from various recording modalities. *Journal of Open Source Software, 9*(102), 6842.](https://joss.theoj.org/papers/10.21105/joss.06842)

- Oppermann, J., Tschentscher, V., **Welzel, J.**, Geritz, J., Hansen, C., Gold, R., Maetzler, W., Scherbaum, R., & Tönges, L. (2024). [Clinical and device-based predictors of improved experience of activities of daily living after a multidisciplinary inpatient treatment for people with Parkinson’s disease: A cohort study. *Therapeutic Advances in Neurological Disorders, 17,* 17562864241277157.](https://doi.org/10.1177/17562864241277157)

- Schaeffer, E., Kluge, A., Schulte, C., Deuschle, C., Bunk, J., **Welzel, J.**, Maetzler, W., & Berg, D. (2024). [Association of misfolded α-synuclein derived from neuronal exosomes in blood with Parkinson’s disease diagnosis and duration. *Journal of Parkinson's Disease, 14*(4), 667-679.](https://content.iospress.com/articles/journal-of-parkinsons-disease/jpd230390)

- Kluge, A., Schaeffer, E., Bunk, J., Sommerauer, M., Röttgen, S., Schulte, C., Roeben, B., von Thaler, A.-K., **Welzel, J.**, Lucius, R., Heinzel, S., Xiang, W., Eschweiler, G. W., Maetzler, W., Suenkel, U., & Berg, D. (2024). [Detecting misfolded α-synuclein in blood years before the diagnosis of Parkinson’s disease. *Movement Disorders, 39*(8), 1289-1299.](https://onlinelibrary.wiley.com/doi/abs/10.1002/mds.29766)

- Poldrack, R. A., Markiewicz, C. J., Appelhoff, S., Ashar, Y. K., Auer, T., Baillet, S., Bansal, S., Beltrachini, L., Benar, C. G., Bertazzoli, G., Bhogawar, S., Blair, R. W., Bortoletto, M., Boudreau, M., Brooks, T. L., Calhoun, V. D., Castelli, F. M., Clement, P., Cohen, A. L., … **Welzel, J.** (2024). [The past, present, and future of the brain imaging data structure (BIDS). *Imaging Neuroscience, 2,* 1-19.](https://doi.org/10.1162/imag_a_00103)

- Jeung, S., Cockx, H., Appelhoff, S., Berg, T., Gramann, K., Grothkopp, S., Warmerdam, E., Hansen, C., & Oostenveld, R., **& BIDS Maintainers** (2024). [Motion-BIDS: An extension to the brain imaging data structure to organize motion data for reproducible research. *Scientific Data, 11*(1), 716.](https://www.nature.com/articles/s41597-024-03559-8) 

- **Welzel, J.**, Güthe, M., Keil, J., Hermann, G., Wolke, R., Maetzler, W., & Becktepe, J. S. (2024). [The interplay of sensory feedback, arousal, and action tremor amplitude in essential tremor. Scientific Reports, 14(1), 4301.](https://www.nature.com/articles/s41598-024-54528-5)

## 2023

- Bindel, L., Mühlberg, C., Pfeiffer, V., Nitschke, M., Müller, A., Wegscheider, M., Rumpf, J.-J., Zeuner, K. E., Becktepe, J. S., **Welzel, J.**, Güthe, M., Classen, J., & Tzvi, E. (2023). [Visuomotor adaptation deficits in patients with essential tremor. *The Cerebellum, 22*(5), 925–937.](https://doi.org/10.1007/s12311-022-01474-5)

## 2022

-   Hansen, C., Ortlieb, C., Romijnders, R., Warmerdam, E., **Welzel, J.**, Geritz, J., & Maetzler, W. (2022). [Reliability of IMU-Derived Temporal Gait Parameters in Neurological Diseases. Sensors, 22(6), 2304.](https://www.mdpi.com/1424-8220/22/6/2304)

-   Scholz, K., Geritz, J., Kudelka, J., Rogalski, M., Niemann, K., Maetzler, C., **Welzel, J.**, Drey, M., Prell, T., & Maetzler, W. (2022). [Static balance and chair-rise performance in neurogeriatric patients: promising Short Physical Performance Battery-derived predictors of fear of falling. Frontiers in medicine, 9.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9253572/)

-   Geritz, J., **Welzel, J.**, Hansen, C., Maetzler, C., Hobert, M. A., Elshehabi, M., Sobczak, A., Kudelka, J., Stiel, C., Hieke, J., & others. (2022). [Does Executive Function Influence Walking in Acutely Hospitalized Patients With Advanced Parkinson's Disease: A Quantitative Analysis. Frontiers in Neurology, 13, 852725.](https://www.frontiersin.org/articles/10.3389/fneur.2022.852725/pdf)

-   Kudelka, J., Geritz, J., **Welzel, J.**, Hildesheim, H., Maetzler, C., Emmert, K., Niemann, K., Hobert, M. A., Pilotto, A., Bergmann, P., & others. (2022). [What contributes most to the SPPB and its subscores in hospitalized geriatric patients: an ICF model-based approach. BMC geriatrics, 22(1), 1-11.](https://bmcgeriatr.biomedcentral.com/articles/10.1186/s12877-022-03358-z)

-   Bindel, L., Muehlberg, C., Pfeiffer, V., Nitschke, M., Mueller, A., Wegscheider, M., Rumpf, J. J., Zeuner, K. E., Becktepe, J. S., **Welzel, J.**, & others. (2022). [Visuomotor Adaptation Deficits in Patients with Essential Tremor. The Cerebellum, 1-13.](https://link.springer.com/article/10.1007/s12311-022-01474-5)

-   Warmerdam, E., Hansen, C., Romijnders, R., Hobert, M. A., **Welzel, J.**, & Maetzler, W. (2022). [Full-Body Mobility Data to Validate Inertial Measurement Unit Algorithms in Healthy and Neurological Cohorts. Data, 7(10), 136.](https://www.mdpi.com/2306-5729/7/10/136)

-   Paschen, S., Hansen, C., **Welzel, J.**, Albrecht, J., Atrsaei, A., Aminian, K., Zeuner, K. E., Romijnders, R., Warmerdam, E., Urban, P. P., & others. (2022). [Effect of Lower Limb vs. Abdominal Compression on Mobility in Orthostatic Hypotension: A Single-Blinded, Randomized, Controlled, Cross-Over Pilot Study in Parkinson’s Disease. Journal of Parkinson's Disease, Preprint, 1-11.](https://content.iospress.com/articles/journal-of-parkinsons-disease/jpd223406)

-   Braun, T., Wiegard, A., Geritz, J., Hansen, C., Tan, K. E., Hildesheim, H., Kudelka, J., Maetzler, C., **Welzel, J.**, Romijnders, R., & others. (2022). [Association between heart failure severity and mobility in geriatric patients: an in-clinic study with wearable sensors](https://www.sciopen.com/article/10.11909/j.issn.1671-5411.2022.09.010)


## 2021

-   Romijnders, R., Warmerdam, E., Hansen, C., **Welzel, J.**, Schmidt, G., & Maetzler, W. (2021). [Validation of IMU-based gait event detection during curved walking and turning in older adults and Parkinson’s Disease patients.](https://link.springer.com/article/10.1186/s12984-021-00828-0) 

-   Thomson, A., Whiteley, R., Hansen, C., **Welzel, J.**, Racinais, S., & Wilson, M. G. (2021). Effect of speed and gradient on plantar force when running on an AlterG® treadmill. BMC Sports Science, Medicine and Rehabilitation, 13(1), 1-8.

-   **Welzel, J.**, Wendtland, D., Warmerdam, E., Romijnders, R., Elshehabi, M., Geritz, J., Berg, D., Hansen, C., & Maetzler, W. (2021). Step length is a promising progression marker in Parkinson’s Disease. Sensors, 21(7), 2292.

-   Hansen, C., Beckbauer, M., Romijnders, R., Warmerdam, E., **Welzel, J.**, Geritz, J., Emmert, K., & Maetzler, W. (2021). Reliability of IMU-derived static balance parameters in neurological diseases. International Journal of Environmental Research and Public Health, 18(7), 3644.

-   Daeglau, M., Zich, C., **Welzel, J.**, Saak, S. K., Scheffels, J. F., & Kranczioch, C. (2021). Event-related desynchronization in motor imagery with EEG neurofeedback in the context of declarative interference and sleep. Neuroimage: Reports, 1(4), 100058.


## 2020

-   Daeglau, M., Zich, C., **Welzel, J.**, Saak, S. K., Scheffels, J. F., & Kranczioch, C. (2020). Motor Imagery EEG neurofeedback skill acquisition in the context of declarative interference and sleep. bioRxiv, 2020-12.

-   Warmerdam, E., Romijnders, R., **Welzel, J.**, Hansen, C., Schmidt, G., & Maetzler, W. (2020). Quantification of arm swing during walking in healthy adults and Parkinson’s Disease patients: Wearable sensor-based algorithm development and validation. Sensors, 20(20), 5963.
-   Daeglau, M., Zich, C., Emkes, R., **Welzel, J.**, Debener, S., & Kranczioch, C. (2020). Investigating priming effects of physical practice on motor imagery-induced event-related desynchronization. Frontiers in psychology, 11, 57.

-   Geritz, J., Maetzold, S., Steffen, M., Pilotto, A., Corrà, M. F., Moscovich, M., Rizzetti, M. C., Borroni, B., Padovani, A., Alpes, A., & others. (2020). Motor, cognitive and mobility deficits in 1000 geriatric patients: protocol of a quantitative observational study before and after routine clinical geriatric treatment—the ComOn-study. BMC geriatrics, 20(1), 1-13.